import { fetchMonthlyReport } from '../../lib/reports'
import { fetchCurrentUser } from '../../lib/auth'
import { fetchUsers } from '../../lib/users'
import { fetchProject } from '../../lib/projects'
import { notFound, redirect } from 'next/navigation'
import AppShell from '../../components/AppShell'
import { Calendar, User, Folder, BarChart3, ArrowLeft } from 'lucide-react'
import Link from 'next/link'
import { format } from 'date-fns'

export default async function MonthlyReportDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const currentUser = await fetchCurrentUser()
  if (!currentUser) {
    redirect('/login')
  }

  try {
    const report = await fetchMonthlyReport(id)
    const [project, users] = await Promise.all([
      fetchProject(report.project_id.toString()),
      fetchUsers()
    ])

    const creator = users.find(u => u.id === report.user_id)
    const creatorName = creator?.profile?.full_name || creator?.username || `User #${report.user_id}`

    const months = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ]

    return (
      <AppShell currentUser={currentUser}>
        <div className='max-w-4xl mx-auto'>
          <Link
            href='/monthly-reports'
            className='mb-6 flex items-center gap-2 text-sm font-medium text-zinc-500 transition-colors hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100'
          >
            <ArrowLeft className='h-4 w-4' />
            Back to Monthly Reports
          </Link>

          <div className='rounded-2xl border border-zinc-200 bg-white p-8 dark:border-zinc-800 dark:bg-zinc-900'>
            <div className='mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between'>
              <div className='flex items-center gap-4'>
                <div className='rounded-xl bg-zinc-100 p-3 dark:bg-zinc-800'>
                  <BarChart3 className='h-6 w-6 text-zinc-600 dark:text-zinc-400' />
                </div>
                <div>
                  <h1 className='text-2xl font-bold text-zinc-900 dark:text-zinc-100'>
                    Monthly Report - {months[report.month - 1]} {report.year}
                  </h1>
                  <p className='text-zinc-500 dark:text-zinc-400'>ID: #{report.id}</p>
                </div>
              </div>
            </div>

            <div className='grid gap-6 sm:grid-cols-3'>
              <div className='rounded-xl border border-zinc-100 bg-zinc-50/50 p-4 dark:border-zinc-800 dark:bg-zinc-900/50'>
                <div className='mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-zinc-500'>
                  <Folder className='h-3.5 w-3.5' />
                  Project
                </div>
                <p className='text-sm font-semibold text-zinc-900 dark:text-zinc-100'>{project.name}</p>
              </div>

              <div className='rounded-xl border border-zinc-100 bg-zinc-50/50 p-4 dark:border-zinc-800 dark:bg-zinc-900/50'>
                <div className='mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-zinc-500'>
                  <User className='h-3.5 w-3.5' />
                  Generated By
                </div>
                <p className='text-sm font-semibold text-zinc-900 dark:text-zinc-100'>{creatorName}</p>
              </div>

              <div className='rounded-xl border border-zinc-100 bg-zinc-50/50 p-4 dark:border-zinc-800 dark:bg-zinc-900/50'>
                <div className='mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-zinc-500'>
                  <Calendar className='h-3.5 w-3.5' />
                  Created At
                </div>
                <p className='text-sm font-semibold text-zinc-900 dark:text-zinc-100'>
                  {format(new Date(report.created_at), 'MMMM d, yyyy')}
                </p>
              </div>
            </div>

            <div className='mt-8 pt-8 border-t border-zinc-100 dark:border-zinc-800'>
              <h3 className='text-lg font-semibold text-zinc-900 dark:text-zinc-100 mb-4'>Details</h3>
              <p className='text-zinc-600 dark:text-zinc-400'>
                This is a system-generated monthly performance report for {project.name} during {months[report.month - 1]} {report.year}.
              </p>
              {/* Add more detailed report content here if available from backend */}
            </div>
          </div>
        </div>
      </AppShell>
    )
  } catch (error) {
    console.error('Error fetching monthly report:', error)
    return notFound()
  }
}
